apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: default
spec:
  encryptedData:
    FOO: AgCcRrNeqGS4knAG1s79FglFsbdV3rnIHSlFS6N0rA5NNx0UCj96evVu+bnVWIVJuGJhQgxBF0BiXKmoQRjdIJuRMtLZbmAsHhZycNdkw3VXRxCefQIwNYGg/kCarbwx7KWOJmuj76HcUYfFeupXkFv2jNNX2Xyrtc50WGIkITM9uyGhIJowq92ilR2fqHvtD6RDgVDzNHMKkiaVpD3iJ5zJ/vKYTi+F3jCMwsmVry87Vs+QE0EHzGCH70eDI3AW3dNf+AJ0Efl/zpAVbaibN+yaP88N35Sk60CjQR7PmZUVJHxchiIh8KnwfMFqNGcNY/qMp+izNoZjXs9c19RmRCHyw5rpZ463Z9BRCOcCTMvKZOwOFaX6T0NXp2JtEzylvl2y9+PPU20bvs+5v4Wh+0E9ikhjXkfDCy75yJwoN+hzYsUyvqMIs12U/xefkHIZCZ5IBCz0Y2yVS2F/ybS14Z2gAVSnIG4Z5SMF7tEpQNxXqiqVP6ZVjlJ+/hR8JuVCP3rQyZZIXTYt+LMeAEf3mAsJGYFtu0ME70Ib/pnsPw+LZLvpXuFNs5tSGm/DAnIX5tt7TMZM8SyuO06bqYzP1PQZgPNoDR2rwaE1t+nMriM8qvSt57PhYhD1vcfO1UBGhy15OhfdYFDC5vJDKQPVw4z6Orb21Ev2LTb3BaltqO8oe70KbR1N68yQ0aUGPIV6Xhtkg1k=
    SOURCE: AgA+WaY/Ea+/GdkzIPqA3364nsT27fpQ2hpOtDLHWElpckaa99ZciCEdPOkxKeHVcOKnlJHWEGTk64u63jXlzkMz233IcB0YDaC2PAO11ZuYO5WLqBlSCBaExtN74Au/n2+WZJLqcnDkRP6XPjquiJ+QqBxAk329PbFhq2eiYKYGH65B1j8OY8lfKXehM7ZPw6bmXd9HVQ9uO+/PQkvlcsjal9zJsh3E0+h8fsODBZ/uUD+MiGiGRHOLb9nHXWTML+D8Sqk70nxni3qHXxVqMzOMq0Kd3vVOs7gTyKrZ5e4vWzBxTKgZ3H2VPixiDtuGdjWBDjHh4b6rVVPUsb95Uxzs5+P3Qw8XWa/HMf/ZLgssa55mI/ZmRTcaEft0u+6AvhnRqCElm/4JtwsD0GPzv7urallKw3g+bG3h+AdpJCTWJ78aPrGjEOiJMR6lL/D4YCLGpDR2C4X2wKOhIPpsJoMHgW1S5T3HHRaFIACltBqvTmbaiHIjbzHpq8+LQXI7Dz1r8RlcNQPJvNDWmdVbnPpJ6+kbH7kutFA5TBAvGKWhnaHc7oDvlV34ZZH9YcJId6U7WD+TqFBOI35ZmoIRQc+FBLeueAMEma+wPqf8dU5Rhl8kqkbH78rqT57ycXVLNyi7peIFgdbinxDwnUxuEdmYPkZTnAZMceGx7LMjTUQsFnEqCgTRaM+BFvEFvoaTOn2BLRcr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: default
    type: Opaque

