version: v2beta1
name: secrets-management-sealed-secrets

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |2-
      create_deployments sealed-secrets-controller
      export ENV=dev
      run_pipelines create-sealed-secret
      create_deployments sealed-secret app
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  deploy:
    run: |-
      export ENV=prod
      run_pipelines create-sealed-secret
      create_deployments sealed-secret app
  create-sealed-secret:
    run: |-
      devspace run fetch-cert
      devspace run seal-secret

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  sealed-secrets-controller:
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: sealed-secrets
        repo: https://bitnami-labs.github.io/sealed-secrets
      upgradeArgs:
        - '--wait'
  sealed-secret:
    kubectl: 
      manifests: [sealed-secret.yaml]
  app:
    kubectl:
      manifests: [../app/pod-reading-secret.yaml]
    namespace: sealed-secret-app

# Use the `commands` section to define repeatable dev workflows for this project 
commands:
  fetch-cert:
    command: |-
      kubeseal --fetch-cert --controller-name=sealed-secrets-controller --controller-namespace=default > pub-cert.pem
  seal-secret:
    command: |-
      kubeseal --cert=pub-cert.pem --format=yaml < ${ENV}-k8s-secret.yaml > sealed-secret.yaml

# Define dependencies to other projects with a devspace.yaml
# dependencies:
#   api:
#     git: https://...  # Git-based dependencies
#     tag: v1.0.0
#   ui:
#     path: ./ui        # Path-based dependencies (for monorepos)
