version: v2beta1
name: secrets-management-sealed-secrets

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |2-
      create_deployments sealed-secrets-controller   # 2. Deploy Helm charts and manifests specfied as "deployments"
      export ENV=dev
      run_pipelines create-sealed-secret
      create_deployments sealed-secret app
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  deploy:
    run: |-
      export ENV=prod
      run_pipelines create-sealed-secret
      create_deployments sealed-secret app
  create-sealed-secret:
    run: |-
      devspace run fetch-cert
      devspace run seal-secret

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  app:
    image: username/app
    dockerfile: ./Dockerfile

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  sealed-secrets-controller:
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: sealed-secrets
        repo: https://bitnami-labs.github.io/sealed-secrets
  sealed-secret:
    kubectl: 
      manifests: [sealed-secret.yaml]
  app:
    kubectl:
      manifests: [../app/pod-reading-secret.yaml]
    namespace: sealed-secret-app
    

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    # Search for the container that runs this image
    imageSelector: username/app
    # Replace the container image with this dev-optimized image (allows to skip image building during development)
    devImage: ghcr.io/loft-sh/devspace-containers/alpine:3
    # Open a terminal and use the following command to start it
    terminal:
      command: ./devspace_start.sh
    # Sync files between the local filesystem and the development container
    sync:
      - path: ./
    # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
    ssh:
      enabled: true
    # Make the following commands from my local machine available inside the dev container
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - command: git

# Use the `commands` section to define repeatable dev workflows for this project 
commands:
  fetch-cert:
    command: |-
      kubeseal --fetch-cert --controller-name=sealed-secrets-controller --controller-namespace=default > pub-cert.pem
  seal-secret:
    command: |-
      kubeseal --cert=pub-cert.pem --format=yaml < ${ENV}-k8s-secret.yaml > sealed-secret.yaml

# Define dependencies to other projects with a devspace.yaml
# dependencies:
#   api:
#     git: https://...  # Git-based dependencies
#     tag: v1.0.0
#   ui:
#     path: ./ui        # Path-based dependencies (for monorepos)
