apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: sealed-secret-app
spec:
  encryptedData:
    FOO: AgDFH7ytFXLOEnMkwsGgjcxMKG6KW1N1mjVyAC7ah2lkhv2/lEfGVc5KPHrzJnFzleP7XWYlH6Zq5DYsdXIvvV9fHkqdjykcQ45yhNRgzoa/ywVcnk/xh1BqAe+fb42xdTH54dNor6jqy59YUBOENUzqw1b9G8fTxStv2Jm0A45HOuPUMudxp92zCwY68SNo1E1NYEAJ3YSX6mVIDDuDCHgsAA/zq+hM1IlIF02m6FBwHQ2EdKGvV0vtrOPuSnOtX2gBc8hYldMg1T65Rk0vfChhyyzCrJsVfW3Y2+u46aqCmikpTIpuVq/5XN0qosgbfnBlMLR5XxmiVwLVXHzSVsG9fOEPQNjWWX+YXr5i30uCUCY1mTUrUz2nkdfZHFWP5HNouZBR9Pw7/gBuCozU1a/tr1VXry9x4g7zgYad9Wx+dvT3Fb618i9Su76XTWaZUUatf1c1Lc5EVFCgqCvlGYt7BmN4GKrUj/flsQlTIyWz7vs0Qw5Lb9ag1b2rHDgLtmMjXkLtctFd3byxFE+4VOtpS+KY5xdkXkz7CS3gHZg3g3tl/yz2anvilv08hSo2jCxELiJ0DeKbxHgOkpwZhPsqMcBD89yg7L1ule4gpA2SNwNqVsrO0uLHSQYKlxNuXZEPcc8Qjv8NDJUwCm6oB+PzoVJIJNFwP3kOY1fmzsVpknuGWseEf6LoSxPQC4NDjzx9U1c=
    SOURCE: AgA6fQkmPAGBWhYS2DNBgYzPyO2e9LLpo73gNdongKZ9gKtyfa4uIIRZrWuWLZjcntC8DoPlYd27UHhuCwA8zq8soVqt6yDSeK98k6EoFuAfKXfC6IXdmx8MgGNbITwXj+6GlsDf8QGnCdkjvmNU3apWaDSJaHjAzftbsGeeRLV9Ia8PhfHUZqYApPPLCMJEm559g/4zDuMrHzLifioRO+zcGX+zTmoc6LlBihKL+736FaMSIq8R5gxerTB9Jj15bq6nyTlm08SwPPMNgbQZEWdgi35S3NIJq1CoJPxmscfzAUA6bp48NT7vIX2T5lbWgIA0xY0/T1pZ8wWcmKjB/Z8+EqnQjIkkxLMhIjLprsiruE2l1rQGJlk4xuBJj1YYmtBreqT4yBkkROIiU+HiUjUk2TqhkWK80bDXfCrDwwz8SUrw06/T7DSjMbz15e2b/++3ejUH5neLK7bGH3nWPXYzi1iCP0JbSqdJnSfc9YH0WlcJWra52TTNG7Sjd8doJ5VJm8Gljy3K8R2LAiHCEzO1VKBT2bY1ovFVVG4bp6Eg4ou8ai4bZH4YvItQYV5nDBcEn+Pm2xpKm5wE6j/G4v+oTI4RiKdSq+hegsofd6vj/em4EWsCUXfwRSJt0xy0Bu0+khNnBu4xsf6Asih5Y5lxTSqtBMD0FUHaMsTgX9sPqKIxgOQFnEZYASSi6P5Bm/sOIOaE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: sealed-secret-app
    type: Opaque

