load('ext://helm_resource', 'helm_resource', 'helm_repo')

# Installing Bitnami Sealed Secrets
helm_repo('bitnami', 'https://bitnami-labs.github.io/sealed-secrets', labels=['sealed-secrets'])
helm_resource('sealed-secrets-controller', 'bitnami/sealed-secrets', namespace='sealed-secrets', flags=['--create-namespace'], resource_deps=['bitnami'], labels=['sealed-secrets'])

# Fetch certkey from cluster
local_resource('fetch-cert',
  cmd='kubeseal --fetch-cert --controller-name=sealed-secrets-controller --controller-namespace=sealed-secrets > pub-cert.pem',
  resource_deps=['sealed-secrets-controller'],
  labels=['sealed-secrets']
)

# Seal secret
local_resource('seal-secret',
  cmd='kubeseal --cert=pub-cert.pem --format=yaml < ../app/k8s-secret.yaml > sealed-secret.yaml',
  resource_deps=['fetch-cert'],
  labels=['sealed-secrets']
)

# Deploying sealed secret
k8s_yaml('sealed-secret.yaml')
k8s_resource(new_name='deploy-sealed-secret', objects=['test-secret:SealedSecret'], resource_deps=['seal-secret'], labels=['sealed-secrets'])

# Read secret
k8s_yaml('../app/pod-reading-secret.yaml')
k8s_resource(workload='reading-secret', resource_deps=['seal-secret'],labels=['app'])