apiVersion: v1
kind: Pod
metadata:
  name: reading-secret
spec:
  containers:
  - name: reading-secret
    image: busybox
    env:
      - name: FOO
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: FOO
      - name: SOURCE
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: SOURCE
    command: ["/bin/sh"]
    args: ["-c", "echo secret $FOO && echo source $SOURCE && sleep 3600"]