version: v2beta1
name: secrets-management-vault-eso

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |2-
      create_deployments consul
      create_deployments vault
      start_dev vault
      create_deployments eso
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  deploy:
    run: |-
      create_deployments external-secret app

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  consul:
    namespace: vault
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: consul
        repo: https://helm.releases.hashicorp.com
      # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
      # You may also use `valuesFiles` to load values from files, e.g. valuesFiles: ["values.yaml"]
      valuesFiles:
      - ./consul-values.yaml
  vault:
    namespace: vault
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: vault
        repo: https://helm.releases.hashicorp.com
      # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
      # You may also use `valuesFiles` to load values from files, e.g. valuesFiles: ["values.yaml"]
      valuesFiles:
      - ./vault-values.yaml
  eso:
    namespace: eso
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: external-secrets
        repo: https://charts.external-secrets.io
  external-secret:
    kubectl: 
      manifests: [external-secret.yaml]
  app:
    kubectl:
      manifests: [../app/pod-reading-secret.yaml]
    namespace: vault-eso-app

dev:
  vault:
    labelSelector:
      app.kubernetes.io/instance: vault
      app.kubernetes.io/name: vault
    namespace: vault
    ports:
    - port: 8200:8200


# Define dependencies to other projects with a devspace.yaml
# dependencies:
#   api:
#     git: https://...  # Git-based dependencies
#     tag: v1.0.0
#   ui:
#     path: ./ui        # Path-based dependencies (for monorepos)
