apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: vault-test-secret
  namespace: vault-eso-app
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-secret
  data:
  - secretKey: ENV
    remoteRef:
      key: test-secret
      property: ENV
  - secretKey: SOURCE
    remoteRef:
      key: test-secret
      property: SOURCE