apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secret-mgmt-talk
spec:
  provider:
      gcpsm:                                  # gcpsm provider
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret              # secret name containing SA key
              key: secret-access-credentials  # key name containing SA key
        projectID: secret-management-talk                  # name of Google Cloud project
